config/routes.rb
Rails.application.routes.draw do
  
  get 'users/new'

  root 'static_pages#home' # => root_path
  get  '/test', to: 'static_pages#test'
  get  '/about',  to: 'static_pages#about'
  get  '/event',  to: 'static_pages#event'
  get  'menus/new' => 'menus#new'
  get  'menus/:id' => 'menus#show'
  post 'menus/:id/destroy' => 'menus#destroy'
  resources :menus

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255}, uniqueness: {case_sensitive: false}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  
  def index
    @menus = Menu.all
  end
  
  def new
    @menu = Menu.new
  end
  
  def create
    @menu = Menu.new(menu_params)
    @menu.save
    redirect_to action: :index
  end
  
  def edit
    @menu = Menu.find(params[:id])
  end
  
  def update
    @menu = Menu.find(params[:id])
    @menu.update_attributes(menu_params)
    redirect_to action: :index
  end
  
  def destroy
    Menu.find_by(id: params[:id]).destroy
    redirect_to action: :index
  end
  
  def show
    @menu = Menu.find_by(id: params[:id])
  end
  
  private
    def menu_params
      params.require(:menu).permit(:name, :price, :calorie, :category)
    end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    @content = Faker::Movie.quote
    @forSlide1 = Faker::Games::Pokemon.name
    @forSlide2 = Faker::Games::Pokemon.name
    @forSlide3 = Faker::Games::Pokemon.name
  end
  
  def about
  end
  
  def event
  end
  
  def test
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleWeb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/menus/edit.html.erb
<h1>Edit</h1>
<div>
  <%= form_for(@menu) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :price %>
      <%= f.text_field :price %>
      
      <%= f.label :calorie %>
      <%= f.text_field :calorie %>
      
      <%= f.label :category %>
      <%= f.select :category, [['main',"main"],['drink',"drink"],['dessert',"dessert"]], include_blank: "SELECT"  %>

      <%= f.submit "Save changes!", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/menus/index.html.erb
<h1>MENU</h1>

<input id="tab01" type="radio" name="tabinput" checked>
<input id="tab02" type="radio" name="tabinput">
<input id="tab03" type="radio" name="tabinput">

<ul class="tabnav">
  <p>Category</p>
  <li><label class="tabnav01" for="tab01">main</label></li>
  <li><label class="tabnav02" for="tab02">drink</label></li>
  <li><label class="tabnav03" for="tab03">dessert</label></li>
</ul>

<div class="tabcontent">

  <% @menus.each do |menu| %>
    <% case menu.category %>
    <% when "main" %>
      <div id="tabcontent01">
        <ul>
        <li>
          <%= link_to(menu.name, "/menus/#{menu.id}") %>
          ￥<%= menu.price %>
          <%= menu.calorie %>cal
          <%= menu.category %>
        </li>
        <%= link_to "edit", "/menus/#{menu.id}/edit" %>
        <%= link_to "delete", "/menus/#{menu.id}/destroy",{method:"post"} %>
        </ul>
      </div>
    <% when "drink" %>
      <div id="tabcontent02">
        <ul>
        <li>
          <%= link_to(menu.name, "/menus/#{menu.id}") %>
          ￥<%= menu.price %>
          <%= menu.calorie %>cal
          <%= menu.category %>
        </li>
        <%= link_to "edit", "/menus/#{menu.id}/edit" %>
        <%= link_to "delete", "/menus/#{menu.id}/destroy",{method:"post"} %>
        </ul>
      </div>
    <% when "dessert" %>
      <div id="tabcontent03">
          <ul>
        <li>
          <%= link_to(menu.name, "/menus/#{menu.id}") %>
          ￥<%= menu.price %>
          <%= menu.calorie %>cal
          <%= menu.category %>
        </li>
        <%= link_to "edit", "/menus/#{menu.id}/edit" %>
        <%= link_to "delete", "/menus/#{menu.id}/destroy",{method:"post"} %>
        </ul>
      </div>
    <% end %>
  <% end %>
  <%= link_to("GO to Create",new_menu_path) %>
</div>

app/views/menus/new.html.erb
<h1>Create</h1>
<div>
  <%= form_for(@menu) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :price %>
      <%= f.text_field :price %>
      
      <%= f.label :calorie %>
      <%= f.text_field :calorie %>
      
      <%= f.label :category %>
      <%= f.select :category, [['main','main'],['drink','drink'],['dessert','dessert']], include_blank: "SELECT"  %>

      <%= f.submit "Create!", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/menus/show.html.erb
<h1><%= @menu.name %></h1>

app/views/shared/_footer.html.erb
<footer>
  <div class="contain">
    <ul>
      <li>
      <%= link_to "https://www.google.co.jp/", target: :_blank do %>
      <span class="fa fa-google">Google</span>
      <% end %>
      </li>
      <li>
      <%= link_to "#", target: :_blank do %>
      <span class="fa fa-twitter">twitter</span>
      <% end %>
      </li>
      <li>
      <%= link_to "#", target: :_blank do %>
      <span class="fa fa-facebook">facebook</span>
      <% end %>
      </li>
    </ul>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="contain">
    <div class="top-wrapper">
      <%= link_to("About","/about") %>
      <%= link_to("Menu", menus_path) %>
      <%= link_to("Event","/event") %>
    </div>
  <%= link_to image_tag("food_gyouza_age",class:"logo"),"/" %>
  <h1>猫耳飯店</h1>
  </div>
</header>

app/views/shared/_menu.html.erb
<% menus.each do |menu| %>
<li>
  <%= link_to(menu.name, "/menus/#{menu.id}") %>
  ￥<%= menu.price %>
  <%= menu.calorie %>cal
  <%= menu.category %>
</li>
    <%= link_to "edit", "/menus/#{menu.id}/edit" %>
    <%= link_to "delete", "/menus/#{menu.id}/destroy",{method:"post"} %>
<% end %>

app/views/static_pages/about.html.erb
<h1>About</h1>

app/views/static_pages/event.html.erb
<h1>Event</h1>

app/views/static_pages/home.html.erb
<h1>HELLO CHINESE FOOD</h1>
<p><%= @content %></p>
<div class="slide-wrapper">
  <div class="change-btn-wrapper">
    <div class="change-btn prev-btn">← prev</div>
    <div class="change-btn next-btn">next →</div>
  </div>
  <ul class="slides">
    <li class="slide active"><%= @forSlide1 %></li>
    <li class="slide"><%= @forSlide2 %></li>
    <li class="slide"><%= @forSlide3 %></li>
  </ul>
  <div class="index-btn-wrapper">
    <div class="index-btn checked">1</div>
    <div class="index-btn">2</div>
    <div class="index-btn">3</div>
  </div>
</div>

app/views/static_pages/test.html.erb
<h1>Ajax#index</h1>
<p id="hoge">赤色になるよ</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>